### ISSUE TITLE
Inference Empy Results

### ISSUE THREAD

**Issue by marcoaleixo** [drc10723/bert_quora_question_pairs#2]
Hi, thank you for the amazing Colab Notebook.
I'm able to reproduce all your results!

Now I'm trying to make a Colab just for Inference tests - https://colab.research.google.com/drive/1yAFsjpHyi0popZ_AoVkmEUlNwG2Vs3CL

But I'm receiveing a empty list as result, any ideia?
I'm using your fine tunned model and using only CPU.

**Comment by dharmendrach** [comment]
I got your issue. Problem is with predict_input_fn function. For TPU batch size must be constant always, so I was adding dummy examples to make batch size 8 and set drop_remainder flag as True. Because of same results were blank as blank input passed. Please set drop_remainder flag to False as below. I have updated same in my Colab notebook. 

`predict_input_fn = run_classifier.input_fn_builder(predict_features,
                                                seq_length=MAX_SEQ_LENGTH,
                                                is_training=False,
                                                drop_remainder=False)`
